### ISSUE TITLE
mobile/small device responsive view: no post/cancel buttons

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#126]
i believe this is a regression?
![localhost_8000_](https://user-images.githubusercontent.com/20133857/47132588-4cb38580-d26a-11e8-8ac8-f828bbdb31fd.png)

/cc @y6nH

**Comment by barzamin** [comment]
i'll try to bisect this tomorrow

**Comment by y6nH** [comment]
Strange. I'll have a look later.

**Comment by barzamin** [comment]
closed via 8c9baa5df8361386a0f471265c2b0b491c9dd5c6
