### ISSUE TITLE
rustodon.glitch.social CD isn't running

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#134]
it's still stuck on 45525c37b. any ideas, @rustodon/ops?

**Comment by RobotDisco** [comment]
Nothing seemed obviously wrong with the deployment stuff; restarted machine and it worked. Based on logs complaning about time offsets I suspect that there was some kind of time drift, going to make sure NTP is working properly but that's the only thing I can think of.

**Comment by RobotDisco** [comment]
Yeah NTP doesn't work out of the box, had to install `ntp` package even though systemd-timesyncd controls everything; weird.

**Comment by barzamin** [comment]
Thanks! :purple_heart:
