### ISSUE TITLE
Build fails with Rust 1.32.0

### ISSUE THREAD

**Issue by khimaros** [rustodon/rustodon#197]
Is there some sort of bug in Cargo's semantic version resolution? 1.32.0 seems like it should be > 1.31.0-nightly. Specific error message:

```
Installed version is: 1.32.0 (2019-01-16). Minimum required: 1.31.0-nightly (2018-10-05).
```

**Comment by barzamin** [comment]
No, you need the -nightly. It looks like you're attempting to use 1.32.0
*stable*, which, even though it's a newer compiler, doesn't have nightly
features.

**Comment by khimaros** [comment]
I see. That makes sense. Thank you!
