### ISSUE TITLE
CI: Produce build artifact that doesn't include unnecessary build output

### ISSUE THREAD

**Issue by RobotDisco** [rustodon/rustodon#20]
I have noticed the rust target/ directory, when compiled, is about a gigabytee ... primarily because of:

```
.../deployment-archive/target/release$ du -hd1
780M	./deps
599M	./build
```

This will bloat any remote server drastically.

Naively I would imagine that a build artifact at this point only requires the rustodon binary and perhaps the migration scripts.

I am not familiar with rust, and all my googles should that rust is still in flux when it comes to best practices for packaging outputs.

Things I would like to do:

- [ ] confirm whether we actually need to keep source and intermediate binaries in the final build artifact
- [ ] modify travis to be more selective about what it includes

**Comment by yipdw** [comment]
Source and intermediates aren't required; the only things you need are:

- the binary at `target/release/rustodon`
- any shared libraries for C dependencies (in rustodon's case, libpq)

**Comment by barzamin** [comment]
Unfortunately, we still need `templates/` (atm). Once I get the Maud stuff working, we'll just need the binary + any static data like CSS.

**Comment by RobotDisco** [comment]
Ok cool. Even with templates/, it sounds like we can definitiely just make sure that travis bundles the appropriate directories. On the assumption everything runs happy if relative to the path of the binary or CWD, this shouldn't be onerous.

**Comment by RobotDisco** [comment]
@barzamin just to confirm, the migrations aren't actually needed as part of the build artifact? I assume I need to run `diesel migration run` at some point though...

**Comment by barzamin** [comment]
The migrations are needed _on the server_, but only when you _run the migrations to update the db_.

**Comment by RobotDisco** [comment]
Oh oops I did this off the cuff after the CI server went down due to lack of space. Ah well.
