### ISSUE TITLE
Consider adding a CSS preprocessor

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#25]
As the frontend grows, I'd like to be able to use SCSS for preprocessing the CSS and templating in variables. If nobody minds my adding Sass as a dependency, I could add it as a step to `build.rs`.

I don't know if this would make CI harder (boop, @yipdw, @RobotDisco).

**Comment by BanjoFox** [comment]
Are you going to do the SCSS from scratch?  I ask because the Bulma.io framework is pretty nice, and it uses SASS.

**Comment by RobotDisco** [comment]
Since travisCI is using trusty as its base, we can probably add a pre-run command to install whatever tools are necessary ... if it needs to be a particularly recent version or requires node maybe like becomes interesting, but should still be doable.

**Comment by RobotDisco** [comment]
@barzamin when a particular tool is decided on, please specify an we can add it to the travis build!

**Comment by barzamin** [comment]
Closed in #28!
