### ISSUE TITLE
Content warnings

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#33]
- [x] Schema column for content warnings on statuses
- [x] Serialization of content warning field to `"summary"` property on AP status objects
- [x] UI for adding CWs to a status when composing (basically just add a form field and make `content_warning` `None` if it's empty and `Some(_)` otherwise)
- [x] UI for displaying CWs on statuses on the profile page and status pages

this is seriously a pretty small change change! things you might want to do:
- [x] factor out the status display logic from the profile and status pages to a single source
- [x] figure out how to do CSS-only content 'show more' content collapses

@dexamphetamine, you wanted something to work on; this might be a great opportunity!

**Comment by dexamphetamine** [comment]
i'll push a WIP for review today :)
