### ISSUE TITLE
Better styling

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#56]
We should probably get a person on this who is actually Good at positioning the boxes.

**Comment by netshade** [comment]
Looking at this ticket and base level work that could be done here, would like to suggest moving templates from `maud` to `tera`, if only to move the work of writing HTML / JS / CSS more closely into the natural form of working w/ that tech, and out of Rust / `maud` dsl.

**Comment by barzamin** [comment]
We initially started out using Tera, but found it had some odd quirks (not handling `Option<_>` in a nice way, not handling structs especially well) that made it a bit rough to use, and eventually switched to maud.

I _agree_ that it would be nice to separate the actual markup-y bits out. I'm planning on refactoring the `routes` module to do this Soon:tm:.

**Comment by netshade** [comment]
Ah cool - thanks, and I apologize for suggesting something else, when really I just meant "markup would be nice and make it easier to contribute".

**Comment by barzamin** [comment]
hmmm, askama looks really good...

**Comment by barzamin** [comment]
@y6nH Oh, exciting! We'd be glad to have help.

We've already switched to Askama (as of #70). As far as a design brief, I know what I need to work on tomorrow :sweat_smile:

**Comment by barzamin** [comment]
omg why is this still open
this is closed via #87, #89, #99.
