### ISSUE TITLE
Rust doesn't accept user feedback

### ISSUE THREAD

**Issue by SoniEx2** [rustodon/rustodon#59]
I'm just gonna say pipes at the start of match branches are a highly disliked Rust feature, i.e. there was a lot of feedback against it, but it still got added to Rust anyway, against the users' feedback.

please don't lock issues just because you don't quite understand them. :/

please try to keep the rust community away from this project, as they'll just poison it.

**Comment by barzamin** [comment]
I wrote [a full response](https://github.com/rustodon/rustodon/issues/58#issuecomment-397351423) to this on the locked issue. Feel free to respond to that here - I'm not locking this issue just yet - but for the reasons outlined in that post, I'm closing this issue too.

**Comment by SoniEx2** [comment]
Oh, okay, thanks for the response. I also like Rust a lot (and I do use it myself - my code is not on github tho), it's a nice language and makes development easy. but some things do raise red flags and I can't really just ignore those... but maybe I'm just being needlessly anxious, only time will tell.
