### ISSUE TITLE
Remove CSS preprocessor

### ISSUE THREAD

**Issue by SoniEx2** [rustodon/rustodon#60]
For default values, use multiple classes, e.g.

```
<div class="default-light-bg navigation"></div>
```

This is better than using CSS preprocessors because unlike CSS preprocessors this makes an attempt to keep your webpages (well, their CSS, at least) small. Smaller webpages = faster loading times.

**Comment by barzamin** [comment]
We use a CSS preprocessor as a convenience. Any increase in code size due to SASS is minimal, and the improvements in maintainability (variables that work on all browsers, mixins, nesting) are vast.
