### ISSUE TITLE
Pick one of TEXT or VARCHAR and stick with it

### ISSUE THREAD

**Issue by ilianaw** [rustodon/rustodon#7]
https://github.com/rustodon/rustodon/pull/5#discussion_r160212969

**Comment by barzamin** [comment]
> **er1n - Today at 5:26 PM**
> i want to use either TEXT or VARCHAR everywhere, and i'm assuming the correct 
> answer here is "just use TEXT"
>
> **beatrix-bitrot - Today at 5:26 PM**
> mmmmmmmmmmmmmmmmmmmmmmmmmmmm
> i suspect there's probably performance consequences for that on the DB but i don't actually know
> if something has a reason to be limited in length i think it's fine to use a varchar for that
> they're much more commonly used than TEXT
> it needn't be [consistent]
> it's a prototype
