### ISSUE TITLE
Zero-length posts should be disallowed

### ISSUE THREAD

**Issue by barzamin** [rustodon/rustodon#71]
As in title.
## Mentoring instructions
Use validator [as in `SignupForm`](https://github.com/rustodon/rustodon/blob/5f2f9fe2f5c461b95bfeaf1d12d1eca0a63ff3cf/src/routes/ui/auth.rs#L74) on `CreateStatusForm`; something like `#[validate(length(min = "1"))]`.

**Comment by ashkitten** [comment]
fixed with #72
