### ISSUE TITLE
User-friendly status URLs (ideally, IRIs, but…)

### ISSUE THREAD

**Issue by marrus-sh** [rustodon/rustodon#74]
This is something I was posting about on Masto and @ashkitten suggested you might want it brought to your attention here as something to think about, so here goes. Note that I'm not really familiar with how Rustodon handles URLs so I'm just assuming that you do things approximately like Mastodon does; feel free to adjust or ignore this issue to meet your actual situation.

 * * *

Right now on Mastodon, status IRIs look like this:

    https://glitch.social/users/kibi/statuses/100280709188146130

And the user-friendly URL version looks like this:

    https://glitch.social/@kibi/100280709188146130

Both of these URLs work fine from a technical standpoint, but they're extremely not user-friendly (user-friendlyn't) when it comes to writing them down or publishing them in print or anything that might involve manual input.

> **Use-cases:**
> + An organization with a Rustodon account might want to print a link to a status on a flier.
> + An individual might want to write down the source of a quote in a notebook for later use.
> + A print publication might want to cite a toot in its bibliography, and readers might want to verify the source.

It might be too late to change the IRI form of statuses (since they are the canonical representation of a status, having them be print-friendly would be *ideal* since they would be the preferred link to cite in a bibliography, but if you have any Rustodon servers currently in production it would mean either grandfathering old URLs or else breaking federation on old posts), but the URL form should be flexible at least. The three following representations should be relatively user-friendly as public-facing URLs:

1.  A *case-insensitive* Base32 representation, omitting the confusable letters `I`, `O`, `S`, and `Z`. (You might also want to replace `L` with `_` or make similar adjustments.)

        https://glitch.social/@kibi/02R24QQ8FPLXG

    The advantage to this approach is that the URL is shorter, contains a wider diversity of characters, and is case-insensitive, which will generally make it easier to write down.

2.  A *case-insensitive* Base32 representation as above, split into hyphenated groups.

        https://glitch.social/@kibi/0-2R24-QQ8F-PLXG

     This is a little longer than the first approach, but much easier for eyes to parse and humans to input.

3.  A *case-sensitive* Base64 representation.

        https://glitch.social/@kibi/0FkRMYQ-9PS

    This gets the maximally short URL, but users may not realize that the URL is supposed to be case-sensitive, and there are a number of easily-confusable characters.

> I've prefixed the above URLs with `0` to distinguish them from decimal URLs, making it easy to set up redirects and support both representations. I don't know if this is something you'll want or need or not.

**Comment by marrus-sh** [comment]
[note that <https://en.wikipedia.org/wiki/Base32> has a number of different Base32 encoding systems for comparison]

**Comment by barzamin** [comment]
I would _love_ to implement something like this. In addition, it's a really good first issue. If anyone wants to take it, I'd be happy to mentor!

**Comment by ashkitten** [comment]
fwiw i'm a fan of the first representation, as it's the most accessible and using base64 wouldn't help much, i think

**Comment by csos95** [comment]
I added a route that matches `/@username/status_id` where status_id is either the integer or base32 representation of the id.
I also changed the status::path_with_account method to use this url format so that it will show in the ui instead of the longer format.  
Are there any other things that need to be changed for this?

**Comment by barzamin** [comment]
closed by #184 and #187!
