### ISSUE TITLE
Create a rustfmt configuration for the project

### ISSUE THREAD

**Issue by ilianaw** [rustodon/rustodon#8]
- [x] Bikeshed a style config (the hard part) (#9)
- [x] Enforce as part of the pull request workflow (probably with Travis)

**Comment by barzamin** [comment]
> ... as part of the [PR] workflow ...

/cc @dexamphetamine

**Comment by barzamin** [comment]
Thanks to @yipdw's work, we now run rustfmt as part of our TravisCI pipeline. Closing!
