### ISSUE TITLE
Expired TLS certificate

### ISSUE THREAD

**Issue by paulcmal** [rustodon/rustodon#86]
Hi,

And thank you for working on rustodon. That's an interesting project to try and reimplement an ActivityPub app in Rust :+1: 

However, i noticed the certificate on https://rustodon.glitch.social expired two days ago. Coming from letsencrypt, it shouldn't be too hard (whether with certbot, acme.sh or others) to have it renewed automagically :)

Let me know if you need help with your cron/ACME setup!

**Comment by barzamin** [comment]
Something was a bit funny with certbot's config, oops! I was off camping since Tuesday last week so I didn't get around to fixing it, but I poked it and it seems fine now.

**Comment by paulcmal** [comment]
Thank you for addressing this, I hope you had a nice camping trip!

Also, don't hesitate to let letsencrypt have a dry-run of renewing to be sure the config is fine this time :D
